apiVersion: v1
kind: Namespace
metadata:
  name: camunda
---
# PostgreSQL Database for HA
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: camunda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: camunda
        - name: POSTGRES_USER
          value: camunda
        - name: POSTGRES_PASSWORD
          value: camunda
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: camunda
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
---
# Camunda HA Deployment with 3 replicas
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda
  namespace: camunda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda
  template:
    metadata:
      labels:
        app: camunda
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: camunda
        image: camunda/camunda-bpm-platform:7.20.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DB_DRIVER
          value: org.postgresql.Driver
        - name: DB_URL
          value: jdbc:postgresql://postgres:5432/camunda
        - name: DB_USERNAME
          value: camunda
        - name: DB_PASSWORD
          value: camunda
        - name: WAIT_FOR
          value: postgres:5432
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /camunda/
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /camunda/
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
---
# Service with SessionAffinity for better clustering behavior
apiVersion: v1
kind: Service
metadata:
  name: camunda
  namespace: camunda
spec:
  selector:
    app: camunda
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
---
# HorizontalPodAutoscaler for auto-scaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: camunda-hpa
  namespace: camunda
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: camunda
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
# PodDisruptionBudget to ensure availability during updates
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: camunda-pdb
  namespace: camunda
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: camunda
