apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-job
  namespace: camunda
spec:
  replicas: 3
  selector:
    matchLabels:
      app: camunda-job
  template:
    metadata:
      labels:
        app: camunda-job
    spec:
      containers:
        - name: camunda-job
          image: camunda/camunda-bpm-platform:7.20.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/camundatest"
            - name: SPRING_DATASOURCE_USERNAME
              value: "camunda"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "camunda"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.postgresql.Driver"
            - name: CAMUNDA_BPM_JOB_EXECUTION_ENABLED
              value: "true"
          livenessProbe:
            httpGet:
              path: /camunda/app/welcome/default/
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /camunda/app/welcome/default/
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
