apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: camunda-job-hpa
  namespace: camunda
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: camunda-job
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
